require('should');

const nock = require('nock');
const zapier = require('zapier-platform-core');

const App = require('../index');
const appTester = zapier.createAppTester(App);

describe('oauth2 app', () => {
  before(() => {
    // It's a good idea to store your Client ID and Secret in the environment rather than in code.
    // This works locally via the `export` shell command and in production by using `zapier env`
    if (!process.env.CLIENT_ID || !process.env.CLIENT_SECRET) {
      throw new Error('For the tests to run, you need to do `export CLIENT_ID=1234 CLIENT_SECRET=asdf`');
    }
  });

  it('generates an authorize URL', () => {
    const bundle = {
      // In production, these will be generated by Zapier and set automatically
      inputData: {
        redirect_uri: 'https://zapier.com/'
      },
      environment: {
        // These will come from your local environment. When running in production, Zapier builds a bundle
        // that includes environment variables you have set with `zapier env` command.
        CLIENT_ID: process.env.CLIENT_ID,
        CLIENT_SECRET: process.env.CLIENT_SECRET
      }
    };

    return appTester(App.authentication.oauth2Config.authorizeUrl, bundle)
      .then((authorizeUrl) => {
        authorizeUrl.should.eql(
          `${process.env.BASE_URL}/oauth/authorize?client_id=${process.env.CLIENT_ID}` +
          `&state=%7B%7Bbundle.inputData.state%7D%7D` +
          `&redirect_uri=https%3A%2F%2Fzapier.com%2F&response_type=code`
        );
      });
  });

  it('can fetch an access token', () => {
    // mock oauth token request
    nock(process.env.BASE_URL)
      .post('/oauth/token')
      .reply(200, JSON.stringify({
        access_token: '0123456789',
      }));

    const bundle = {
      inputData: {
        // In production, Zapier passes along whatever code your API set in the query params when it redirects
        // the user's browser to the `redirect_uri`
        code: 'one_time_code',
      },
      environment: {
        CLIENT_ID: process.env.CLIENT_ID,
        CLIENT_SECRET: process.env.CLIENT_SECRET
      },
      cleanedRequest: {
        querystring: {
          code: 'one_time_code'
        }
      },
      rawRequest: {
        querystring: "?code=one_time_code"
      }
    };

    return appTester(App.authentication.oauth2Config.getAccessToken, bundle)
      .then((result) => {
        result.access_token.should.eql('0123456789');
      });
  });

  it('includes the access token in future requests', () => {
    // mock test to graphql to see if user is authenticated
    nock(process.env.BASE_URL)
      .post('/graphql')
      .reply(200, JSON.stringify({
        data: {
          viewer: {
            username: "alapaca"
          }
        }
      }));

    const bundle = {
      authData: {
        access_token: '0123456789',
      },
    };

    return appTester(App.authentication.test, bundle)
      .then((result) => {
        result.should.have.property('username');
      });
  });
});
